# Generated by Django 5.1.3 on 2024-12-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CUENTA CORRIENTE PESOS', 'Cuenta Corriente Pesos'), ('CUENTA CORRIENTE DOLARES', 'Cuenta Corriente Dolares')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(choices=[('HIPOTECARIO', 'Hipotecario'), ('PRENDARIO', 'Prendario'), ('PERSONAL', 'Personal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('DEBITO', 'DEBITO'), ('CREDITO', 'Credito')], max_length=50),
        ),
    ]
