# Generated by Django 5.1.3 on 2024-12-06 04:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cuenta_tipo_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_emicion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='marca',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], default='VISA', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 4, 16, 27, 27713, tzinfo=datetime.timezone.utc)),
        ),
    ]
