# Generated by Django 5.1.3 on 2024-12-06 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tarjeta_fecha_emicion_tarjeta_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 4, 26, 49, 477513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('DEBITO', 'Debito'), ('CREDITO', 'Credito')], max_length=50),
        ),
    ]
