# Generated by Django 5.1.4 on 2024-12-06 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tarjeta_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 6, 23, 36, 10, 353590, tzinfo=datetime.timezone.utc)),
        ),
    ]
