# Generated by Django 5.1.3 on 2024-12-07 21:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tarjeta_fecha_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 7, 21, 43, 45, 353897, tzinfo=datetime.timezone.utc)),
        ),
    ]
