# Generated by Django 5.1.3 on 2024-12-07 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cliente_user_alter_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 7, 21, 46, 35, 157499, tzinfo=datetime.timezone.utc)),
        ),
    ]
