# Generated by Django 5.1.3 on 2024-12-07 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cliente_user_alter_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 7, 22, 35, 20, 572052, tzinfo=datetime.timezone.utc)),
        ),
    ]
