# Generated by Django 5.1.3 on 2024-12-08 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='matias!123', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 8, 1, 8, 39, 222796, tzinfo=datetime.timezone.utc)),
        ),
    ]
