# Generated by Django 5.1.3 on 2024-12-08 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cliente_contrasena_alter_tarjeta_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 8, 1, 10, 43, 205558, tzinfo=datetime.timezone.utc)),
        ),
    ]
