# Generated by Django 5.1.3 on 2024-12-08 21:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cliente_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='12345678', max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.datetime(2025, 12, 8, 21, 52, 44, 577122, tzinfo=datetime.timezone.utc)),
        ),
    ]
