# Generated by Django 5.1.3 on 2024-12-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_cliente_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
    ]
